### PR TITLE
added unit depths & changes to Hugging Face datasets

### PR DESCRIPTION
**Pull request by yzhang511**

### CODE REVIEW

**Comment by colehurwitz** [comment]
How much of the code in the ndt1.py file is for ndt? Should we maybe have the Masker + tokenization + data preparation in different files @PPWangyc for reusuability and modularity?

**Comment by colehurwitz** [comment]
Looks great though!

**Comment by colehurwitz** [comment]
The depths will be super useful. Glad you added this @yzhang511

**Comment by PPWangyc** [comment]
> How much of the code in the ndt1.py file is for ndt? Should we maybe have the Masker + tokenization + data preparation in different files @PPWangyc for reusuability and modularity?

Hi @colehurwitz , the code in ndt1.py is all for ndt. I think for current stage, we don't need to change a lot, since we are conducting ssl test on it.

**Comment by colehurwitz** [comment]
Sounds good. I think the PR looks good then! Feel free to merge when ready @PPWangyc @yzhang511

**Comment by colehurwitz** [comment]
We can store all these results in a table and using wandb :)

**Comment by yzhang511** [comment]
Sounds good, I just learned about wandb today :)

**Comment by colehurwitz** [comment]
Ready to merge? @yzhang511

**Comment by yzhang511** [comment]
Updates:
1. Add more hyper-param options, e.g., dropout, to decoders 
2. Give option to save using wandb
3. Add multi-session data loaders and model
4. Add options for regression or classification
5. Changed data splits to compare to poyo
6. Ready to be run on clusters

**Comment by colehurwitz** [comment]
Can we merge this into main soon? The PR is getting pretty long!

**Comment by yzhang511** [comment]
Yes, I think this thread is ready to be merged now :)

**Comment by colehurwitz** [comment]
Ok, you can merge when ready :)

**Pull request merged**
