### PR TITLE
data loading and dataset restructure

### PR DESCRIPTION
**Pull request by yzhang511**
1. switched from loading recording segments within trials only to full recording including both trials and non-trials
2. restructured the Hugging Face datasets

### CODE REVIEW

**Comment by colehurwitz** [comment]
Taking a look now!

**Comment by colehurwitz** [comment]
The PR looks great! Some small comments:

- Update the doc strings for spike_data_per_interval to remove the word trial
- Might want to parallelize over intervals later if this is a bottleneck
- I think trials_only is redundant. You can just check if trials_df is not None.
- Would be nice to quantify what percentage of the data we lose per EID from the behavior skipping

Let’s replace: 
```
good_trial[i] = False
target_times_list.append(None)
target_vals_list.append(None) with:
```
with a function
```
def skip_trial(index, skip_reason):
    # print(f'Skipping trial {index} due to: {skip_reason}')
    good_trial[index] = False
    target_times_list.append(None)
    target_vals_list.append(None)
```
This will save code repeating and we can change the behavior easily later.

**Comment by colehurwitz** [comment]
The dataset metadata changes are good

**Comment by yzhang511** [comment]
Sounds good, I will address these comments. 2 questions:

   - Might want to parallelize over intervals later if this is a bottleneck
   - do you mean parallelizing computing spike count for each interval?
   - Would be nice to quantify what percentage of the data we lose per EID
   from the behavior skipping - could you please clarify on this?

**Comment by colehurwitz** [comment]
- Yes, the binning of behavior and spiking activity could be parallelizing instead of a for loop if we have long recordings. May not be needed if this is fast.

- Every time we skip a trial of behavior, we lose information. I am curious how many trials we have to skip on average per EID. It would be useful for IBL to know this percentage.

**Comment by colehurwitz** [comment]
I think we can merge if you fix the other parts. The parallelization + behavioral information loss can be for the future.

**Comment by colehurwitz** [comment]
Looks great. Merging!

**Pull request merged**
